// Generated by scripts/export_contract.py. DO NOT EDIT.
// Runtime constraints and cross-field checks require validation; these are static types.
export const SCHEMA_VERSION = "0.1.0" as const;

export interface Article {
  schema_version: "0.1.0";
  record_type: "article";
  article_id: string;
  original_url: string;
  canonical_url: string;
  title: string;
  article_kind: "announcement" | "documentation" | "blog" | "changelog" | "security" | "news" | "other";
  authors: Array<string> | null;
  language_code: string | null;
  published_at: string | null;
  published_date: string | null;
  published_precision: "timestamp" | "date" | "unknown";
  updated_at: string | null;
  content_status: "full" | "snippet" | "unavailable";
  content_text: string | null;
  content_sha256: string | null;
  content_available_at: string | null;
  technology_mentions: Array<TechnologyMention>;
  repo_ids: Array<string>;
  package_ids: Array<string>;
  provenance: Provenance;
}

export interface CollectionMetadata {
  collector_name: string;
  collector_version: string;
  started_at: string;
  finished_at: string;
  requested_time_range: TimeRange | null;
  pages_fetched: number;
  records_emitted: number;
  records_rejected: number;
  pagination_complete: boolean;
  next_cursor: string | null;
  coverage: Array<Coverage>;
  rate_limit_remaining: number | null;
  rate_limit_reset_at: string | null;
}

export interface CollectionRequest {
  schema_version: "0.1.0";
  record_type: "collection_request";
  request_id: string;
  run_id: string;
  collector_name: string;
  source: "github_rest" | "github_graphql" | "pypi_json" | "pypi_index" | "pypi_bigquery" | "gh_archive" | "deps_dev" | "osv" | "project_docs" | "web_article" | "source_archive" | "technology_catalog";
  subjects: Array<CollectionSubject>;
  record_kinds: Array<"github_repository" | "package_release" | "repository_activity" | "dependency_metadata" | "article" | "technology_entity" | "security_advisory">;
  time_range: TimeRange | null;
  cutoff_at: string | null;
  cursor: string | null;
  max_pages: number;
  max_records: number;
}

export interface CollectionResult {
  schema_version: "0.1.0";
  record_type: "collection_result";
  request_id: string;
  run_id: string;
  source: "github_rest" | "github_graphql" | "pypi_json" | "pypi_index" | "pypi_bigquery" | "gh_archive" | "deps_dev" | "osv" | "project_docs" | "web_article" | "source_archive" | "technology_catalog";
  status: "complete" | "partial" | "failed";
  records: Array<RawRecord>;
  errors: Array<DataError>;
  metadata: CollectionMetadata;
}

export interface CollectionSubject {
  repo_id: string | null;
  repo_full_name: string | null;
  package_id: string | null;
  url: string | null;
}

export interface Coverage {
  data_group: "repo_identity" | "releases" | "commits" | "contributors" | "issues" | "pull_requests" | "dependencies" | "articles" | "technologies" | "security_advisories";
  status: "complete" | "partial" | "unavailable" | "not_applicable";
  time_range: TimeRange | null;
  records_observed: number;
  missing_reason: "not_in_source" | "not_collected" | "unavailable" | "parse_error" | "not_applicable" | "ambiguous" | "historical_unavailable" | null;
}

export interface DataError {
  code: "network_error" | "http_error" | "rate_limited" | "not_found" | "not_mapped" | "unsupported_record_type" | "validation_error" | "parse_error" | "insufficient_history" | "schema_version_mismatch";
  message: string;
  retryable: boolean;
  source_record_id: string | null;
  raw_record_id: string | null;
}

export interface DependencyRequirement {
  package_id: string;
  version_specifier: string;
  environment_marker: string | null;
  extras: Array<string>;
  dependency_kind: "runtime" | "optional" | "build" | "development";
}

export interface GitHubRepository {
  schema_version: "0.1.0";
  record_type: "github_repository";
  identity: RepoIdentity;
  description: string | null;
  visibility: "public" | "private" | "internal";
  is_fork: boolean;
  is_template: boolean;
  is_archived: boolean;
  mirror_url: string | null;
  primary_language: string | null;
  language_bytes: Array<LanguageBytes> | null;
  created_at: string;
  updated_at: string;
  pushed_at: string | null;
  stargazers_count: number | null;
  forks_count: number | null;
  open_issues_and_prs_count: number | null;
  provenance: Provenance;
}

export type JsonValue = boolean | number | number | string | Array<JsonValue> | { [key: string]: JsonValue } | null;

export interface LanguageBytes {
  language: string;
  bytes_count: number;
}

export interface MissingField {
  field_path: string;
  reason: "not_in_source" | "not_collected" | "unavailable" | "parse_error" | "not_applicable" | "ambiguous" | "historical_unavailable";
  detail: string | null;
}

export interface NormalizationRequest {
  schema_version: "0.1.0";
  record_type: "normalization_request";
  request_id: string;
  run_id: string;
  records: Array<RawRecord>;
}

export interface NormalizationResult {
  schema_version: "0.1.0";
  record_type: "normalization_result";
  request_id: string;
  run_id: string;
  normalizer_version: string;
  status: "complete" | "partial" | "failed";
  input_record_count: number;
  processed_record_count: number;
  rejected_record_count: number;
  output_record_count: number;
  records: Array<GitHubRepository | TechnologyEntity | Article | PackageRelease | RepositoryActivity>;
  errors: Array<DataError>;
}

export interface PackageRelease {
  schema_version: "0.1.0";
  record_type: "package_release";
  package_id: string;
  repo_id: string | null;
  version: string;
  uploaded_at: string;
  requires_python: string | null;
  dependencies: Array<DependencyRequirement> | null;
  is_yanked: boolean | null;
  yanked_reason: string | null;
  yanked_status_at: string | null;
  provenance: Provenance;
}

export interface PackageSnapshot {
  schema_version: "0.1.0";
  record_type: "package_snapshot";
  package_id: string;
  repo_id: string;
  repo_group_id: string;
  cutoff_at: string;
  horizon_months: 12;
  horizon_end_at: string;
  features: SnapshotFeatures;
  coverage: Array<Coverage>;
  missing_fields: Array<MissingField>;
  raw_record_ids: Array<string>;
}

export interface Provenance {
  source: "github_rest" | "github_graphql" | "pypi_json" | "pypi_index" | "pypi_bigquery" | "gh_archive" | "deps_dev" | "osv" | "project_docs" | "web_article" | "source_archive" | "technology_catalog";
  source_url: string;
  retrieved_at: string;
  valid_at: string;
  available_at: string | null;
  temporal_basis: "observation" | "historical_reconstruction";
  raw_record_ids: Array<string>;
  missing_fields: Array<MissingField>;
}

export interface RawRecord {
  schema_version: "0.1.0";
  record_type: "raw_record";
  raw_record_id: string;
  run_id: string;
  source: "github_rest" | "github_graphql" | "pypi_json" | "pypi_index" | "pypi_bigquery" | "gh_archive" | "deps_dev" | "osv" | "project_docs" | "web_article" | "source_archive" | "technology_catalog";
  source_record_type: "github_repository" | "package_release" | "repository_activity" | "dependency_metadata" | "article" | "technology_entity" | "security_advisory";
  source_record_id: string | null;
  repo_id: string | null;
  package_id: string | null;
  source_url: string;
  retrieved_at: string;
  event_at: string | null;
  available_at: string | null;
  http_status: number | null;
  raw_body_sha256: string | null;
  payload: { [key: string]: JsonValue };
}

export interface RepoIdentity {
  repo_id: string;
  github_repo_id: string;
  github_node_id: string | null;
  repo_full_name: string;
  repo_url: string;
  known_urls: Array<string>;
}

export interface RepositoryActivity {
  schema_version: "0.1.0";
  record_type: "repository_activity";
  activity_id: string;
  repo_id: string;
  activity_kind: "commit" | "issue_opened" | "issue_closed" | "issue_reopened" | "pr_opened" | "pr_closed" | "pr_reopened" | "pr_merged" | "comment";
  source_object_id: string;
  event_at: string;
  actor_id: string | null;
  actor_is_bot: boolean | null;
  provenance: Provenance;
}

export interface SnapshotBuildRequest {
  schema_version: "0.1.0";
  record_type: "snapshot_build_request";
  request_id: string;
  run_id: string;
  package_id: string;
  repository: RepoIdentity;
  cutoff_at: string;
  horizon_months: 12;
  releases: Array<PackageRelease>;
  activities: Array<RepositoryActivity>;
  coverage: Array<Coverage>;
}

export interface SnapshotBuildResult {
  schema_version: "0.1.0";
  record_type: "snapshot_build_result";
  request_id: string;
  run_id: string;
  builder_version: string;
  status: "complete" | "partial" | "failed";
  snapshot: PackageSnapshot | null;
  errors: Array<DataError>;
}

export interface SnapshotFeatures {
  package_age_days: number | null;
  releases_total: number | null;
  days_since_latest_release: number | null;
  release_count_3m: number | null;
  release_count_6m: number | null;
  release_count_12m: number | null;
  commit_count_3m: number | null;
  commit_count_6m: number | null;
  commit_count_12m: number | null;
  contributor_count_12m: number | null;
  issue_opened_count_12m: number | null;
  issue_closed_count_12m: number | null;
  pr_opened_count_12m: number | null;
  pr_merged_count_12m: number | null;
}

export interface TechnologyEntity {
  schema_version: "0.1.0";
  record_type: "technology_entity";
  technology_id: string;
  slug: string;
  name: string;
  category: "language" | "framework" | "library" | "runtime" | "database" | "developer_tool" | "platform" | "standard";
  aliases: Array<string>;
  description: string | null;
  official_urls: Array<string>;
  repo_ids: Array<string>;
  package_ids: Array<string>;
  lifecycle_status: "active" | "deprecated" | "end_of_life" | "unknown";
  status_evidence_url: string | null;
  provenance: Provenance;
}

export interface TechnologyLinkRequest {
  schema_version: "0.1.0";
  record_type: "technology_link_request";
  request_id: string;
  run_id: string;
  articles: Array<Article>;
  technology_entities: Array<TechnologyEntity>;
}

export interface TechnologyLinkResult {
  schema_version: "0.1.0";
  record_type: "technology_link_result";
  request_id: string;
  run_id: string;
  linker_version: string;
  status: "complete" | "partial" | "failed";
  articles: Array<Article>;
  errors: Array<DataError>;
}

export interface TechnologyMention {
  technology_id: string;
  matched_text: string;
  confidence: number;
  match_method: "dictionary" | "manual" | "model";
  extractor_version: string;
}

export interface TimeRange {
  start_at: string;
  end_at: string;
}

export type ContractRecord = RawRecord | GitHubRepository | TechnologyEntity | Article | PackageRelease | RepositoryActivity | CollectionRequest | CollectionResult | NormalizationRequest | NormalizationResult | TechnologyLinkRequest | TechnologyLinkResult | PackageSnapshot | SnapshotBuildRequest | SnapshotBuildResult;

export interface Collector { collect(request: CollectionRequest): Promise<CollectionResult>; }
export interface Normalizer { normalize(request: NormalizationRequest): Promise<NormalizationResult>; }
export interface TechnologyLinker { link(request: TechnologyLinkRequest): Promise<TechnologyLinkResult>; }
export interface SnapshotBuilder { build(request: SnapshotBuildRequest): Promise<SnapshotBuildResult>; }
